# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Depoly to tencent cloud server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      DEPLOYMENT_HOST: kherrisan.cn

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Pull, build and start next.js server
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        # Command(s) to execute on the remote server.
        command: |
          export DEPLOYMENT_HOST=kherrisan.cn
          cd /home/ubuntu/react-notion-blog
          git pull
          npm i
          npm run build
        hosts: ${{ secrets.SERVER_IP }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
